version: 1.0.0
publish_to: none
name: web_socket_server
description: A web socket server library for Dart.
repository: https://github.com/Jebiel/web_socket_server

environment:
  sdk: ^3.0.0

dependencies:
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
